version: '3.8'

services:
  apifallback:
    image: apifallback:latest
    container_name: apifallback_prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_PATH=/app/data/data.db
      - REDIS_ADDR=redis:6379
      - REDIS_DB=0
      - API_TIMEOUT=30s
      - MAX_CONCURRENCY=20
      - RATE_LIMIT=200
      - RATE_LIMIT_WINDOW=1m
      - HEALTH_CHECK_INTERVAL=5m
      - LOG_LEVEL=info
      # API Sources Configuration
      - MULTIPLESCRAPE_URL=http://multiplescrape:8081
      - WINBUTV_URL=http://winbutv:8082
      - SAMEHADAKU_URL=https://samehadaku.email
      - OTAKUDESU_URL=https://otakudesu.quest
      - KUSONIME_URL=https://kusonime.com
    volumes:
      - apifallback_data:/app/data
    depends_on:
      - redis
    networks:
      - apifallback_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  redis:
    image: valkey/valkey:7-alpine
    container_name: apifallback_redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - apifallback_network
    command: valkey-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --save 900 1 --save 300 10 --save 60 10000
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: apifallback_nginx
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - apifallback
    networks:
      - apifallback_network
    profiles:
      - with-nginx

volumes:
  apifallback_data:
    driver: local
  redis_data:
    driver: local

networks:
  apifallback_network:
    driver: bridge