basePath: /
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A robust API fallback service for anime content with automatic failover
    capabilities
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: API Fallback Service
  version: "1.0"
paths:
  /api/categories/names:
    get:
      consumes:
      - application/json
      description: Returns list of all active category names for dynamic API documentation
      produces:
      - application/json
      responses:
        "200":
          description: List of available category names
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties: true
            type: object
      summary: Get available category names
      tags:
      - System
  /api/v1/anime-detail:
    get:
      consumes:
      - application/json
      description: Retrieve detailed information about a specific anime from all available
        APIs. Requires anime identifier (id, slug, or anime_slug). Uses fallback mechanism
        when primary APIs fail.
      parameters:
      - description: Anime ID (alternative to slug/anime_slug)
        in: query
        name: id
        type: string
      - description: Anime slug (alternative to id/anime_slug)
        in: query
        name: slug
        type: string
      - description: Anime slug (alternative to id/slug)
        in: query
        name: anime_slug
        type: string
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated anime details from available sources
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - missing required anime identifier
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not found - anime not found in any source
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get anime details from multiple sources with fallback
      tags:
      - Detail
  /api/v1/anime-terbaru:
    get:
      consumes:
      - application/json
      description: Retrieve aggregated latest anime releases from all available APIs
        with automatic fallback mechanism
      parameters:
      - default: 1
        description: Page number for pagination
        in: query
        name: page
        type: integer
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated latest anime list from multiple sources with metadata
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - invalid parameters
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get latest anime from multiple sources
      tags:
      - Anime
  /api/v1/episode-detail:
    get:
      consumes:
      - application/json
      description: Retrieve detailed information about a specific episode from all
        available APIs. Requires episode identifier (id, episode_url, or episode_slug).
        Uses automatic fallback mechanism.
      parameters:
      - description: Episode ID (alternative to episode_url/episode_slug)
        in: query
        name: id
        type: string
      - description: Episode URL (alternative to id/episode_slug)
        in: query
        name: episode_url
        type: string
      - description: Episode slug (alternative to id/episode_url)
        in: query
        name: episode_slug
        type: string
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated episode details from available sources
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - missing required episode identifier
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not found - episode not found in any source
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get episode details from multiple sources with fallback
      tags:
      - Detail
  /api/v1/home:
    get:
      consumes:
      - application/json
      description: Retrieve aggregated home page content from multiple anime APIs
        with fallback mechanism. The system automatically calls all available primary
        APIs and aggregates the results.
      parameters:
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated home page content with sources info
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - invalid category
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get home page content from multiple anime sources
      tags:
      - Anime
  /api/v1/jadwal-rilis:
    get:
      consumes:
      - application/json
      description: Retrieve aggregated anime release schedule for all days from multiple
        APIs with automatic fallback
      parameters:
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated anime release schedule with sources info
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - invalid category
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get anime release schedule from multiple sources
      tags:
      - Anime
  /api/v1/jadwal-rilis/{day}:
    get:
      consumes:
      - application/json
      description: Retrieve aggregated anime release schedule for a specific day from
        multiple APIs
      parameters:
      - description: Day of the week (senin, selasa, rabu, kamis, jumat, sabtu, minggu)
        in: path
        name: day
        required: true
        type: string
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated anime release schedule for the day with sources
            info
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - invalid day or category
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get anime release schedule by day from multiple sources
      tags:
      - Anime
  /api/v1/movie:
    get:
      consumes:
      - application/json
      description: Retrieve aggregated anime movie listings from all available APIs
        with fallback mechanism
      parameters:
      - default: 1
        description: Page number for pagination
        in: query
        name: page
        type: integer
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated anime movie list from multiple sources
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - invalid parameters
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Get anime movies from multiple sources
      tags:
      - Movie
  /api/v1/search:
    get:
      consumes:
      - application/json
      description: Search for anime by query string across all available APIs. Aggregates
        search results from multiple sources with automatic fallback mechanism.
      parameters:
      - description: Search query string - title, genre, or keyword to search for
        in: query
        name: q
        required: true
        type: string
      - default: 1
        description: Page number for pagination
        in: query
        name: page
        type: integer
      - default: anime
        description: Content category for API routing - dynamically loaded from database
        in: query
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Aggregated search results from multiple sources with metadata
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request - missing or empty search query
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not found - no results found in any source
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - all API sources failed
          schema:
            additionalProperties: true
            type: object
      summary: Search anime from multiple sources with fallback
      tags:
      - Search
  /dashboard/cache/clear:
    delete:
      consumes:
      - application/json
      description: Clear cache to force fresh normalized responses from API sources
      parameters:
      - description: Endpoint to clear cache for (e.g., /api/v1/anime-detail)
        in: query
        name: endpoint
        type: string
      - default: anime
        description: Category to clear cache for
        in: query
        name: category
        type: string
      - description: Anime slug parameter for specific cache key
        in: query
        name: anime_slug
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Cache cleared successfully
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
      summary: Clear cache for specific endpoint
      tags:
      - Admin
  /dashboard/health:
    get:
      consumes:
      - application/json
      description: Retrieve current health status, response times, and availability
        of all registered API sources
      produces:
      - application/json
      responses:
        "200":
          description: Health status data for all API sources with response times
            and availability
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal server error - failed to retrieve health status
          schema:
            additionalProperties: true
            type: object
      summary: Get health status of all API sources
      tags:
      - System
  /health:
    get:
      consumes:
      - application/json
      description: Basic health check endpoint to verify the service is running and
        operational
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy and operational
          schema:
            additionalProperties: true
            type: object
      summary: Service health check
      tags:
      - System
schemes:
- http
- https
swagger: "2.0"
tags:
- description: Anime related endpoints
  name: Anime
- description: Movie related endpoints
  name: Movie
- description: Search functionality
  name: Search
- description: Health check endpoints
  name: Health
